CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Personas" (
    "IdPersona" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "Apellidos" character varying(100) NOT NULL,
    "FechaNacimiento" timestamp with time zone NOT NULL,
    "Genero" text NOT NULL,
    "DUI" character varying(10) NOT NULL,
    "NIT" character varying(17) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "Telefono" character varying(9) NOT NULL,
    "Direccion" character varying(250) NOT NULL,
    "NumeroAFP" character varying(20),
    "TipoAFP" character varying(50),
    CONSTRAINT "PK_Personas" PRIMARY KEY ("IdPersona")
);

CREATE TABLE "Atestados" (
    "IdAtestado" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdPersona" integer NOT NULL,
    "TipoAtestado" character varying(100) NOT NULL,
    "RutaArchivo" character varying(500) NOT NULL,
    "NombreOriginalArchivo" character varying(255),
    "ExtensionArchivo" character varying(10),
    "FechaSubida" timestamp with time zone NOT NULL,
    "FechaVencimiento" timestamp with time zone,
    "SubidoPor" character varying(100),
    "Activo" boolean NOT NULL,
    "Comentarios" character varying(500),
    CONSTRAINT "PK_Atestados" PRIMARY KEY ("IdAtestado"),
    CONSTRAINT "FK_Atestados_Personas_IdPersona" FOREIGN KEY ("IdPersona") REFERENCES "Personas" ("IdPersona") ON DELETE CASCADE
);

CREATE TABLE "Directivos" (
    "IdDirectivo" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdPersona" integer NOT NULL,
    "CargoDirectivo" text NOT NULL,
    "FechaInicioMandato" timestamp with time zone NOT NULL,
    "FechaFinMandato" timestamp with time zone,
    "TipoMiembro" text NOT NULL,
    CONSTRAINT "PK_Directivos" PRIMARY KEY ("IdDirectivo"),
    CONSTRAINT "FK_Directivos_Personas_IdPersona" FOREIGN KEY ("IdPersona") REFERENCES "Personas" ("IdPersona") ON DELETE CASCADE
);

CREATE TABLE "Empleados" (
    "IdEmpleado" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdPersona" integer NOT NULL,
    "CodigoEmpleado" character varying(50) NOT NULL,
    "FechaContratacion" timestamp with time zone NOT NULL,
    "Puesto" character varying(100) NOT NULL,
    "Salario" numeric(18,2) NOT NULL,
    "Departamento" character varying(100) NOT NULL,
    "Estado" integer NOT NULL,
    "FechaFinContrato" timestamp with time zone,
    "MotivoFinalizacion" character varying(500),
    "TipoFinalizacion" integer,
    CONSTRAINT "PK_Empleados" PRIMARY KEY ("IdEmpleado"),
    CONSTRAINT "FK_Empleados_Personas_IdPersona" FOREIGN KEY ("IdPersona") REFERENCES "Personas" ("IdPersona") ON DELETE CASCADE
);

CREATE TABLE "NivelesEducativos" (
    "IdNivelEducativo" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdPersona" integer NOT NULL,
    "GradoAcademico" character varying(100) NOT NULL,
    "Institucion" character varying(200),
    "TituloObtenido" character varying(200),
    "FechaInicio" timestamp with time zone,
    "FechaFin" timestamp with time zone,
    "Comentarios" character varying(500),
    CONSTRAINT "PK_NivelesEducativos" PRIMARY KEY ("IdNivelEducativo"),
    CONSTRAINT "FK_NivelesEducativos_Personas_IdPersona" FOREIGN KEY ("IdPersona") REFERENCES "Personas" ("IdPersona") ON DELETE CASCADE
);

CREATE TABLE "HistorialDirectivo" (
    "IdHistorialDirectivo" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdDirectivo" integer NOT NULL,
    "Cargo" character varying(100) NOT NULL DEFAULT '',
    "FechaInicioMandato" timestamp with time zone NOT NULL,
    "FechaFinMandato" timestamp with time zone,
    "TipoMandato" character varying(50) NOT NULL DEFAULT '',
    "Comentarios" character varying(500),
    "RegistradoPor" character varying(255),
    "FechaRegistro" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HistorialDirectivo" PRIMARY KEY ("IdHistorialDirectivo"),
    CONSTRAINT "FK_HistorialDirectivo_Directivos_IdDirectivo" FOREIGN KEY ("IdDirectivo") REFERENCES "Directivos" ("IdDirectivo") ON DELETE CASCADE
);

CREATE TABLE "CapacitacionesEmpleados" (
    "IdCapacitacionEmpleado" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdEmpleado" integer NOT NULL,
    "NombreCurso" text NOT NULL,
    "Institucion" text,
    "FechaInicio" timestamp with time zone,
    "FechaFin" timestamp with time zone,
    "CertificadoObtenido" boolean NOT NULL,
    "RutaCertificado" text,
    "Comentarios" text,
    "EmpleadoIdEmpleado" integer NOT NULL,
    CONSTRAINT "PK_CapacitacionesEmpleados" PRIMARY KEY ("IdCapacitacionEmpleado"),
    CONSTRAINT "FK_CapacitacionesEmpleados_Empleados_EmpleadoIdEmpleado" FOREIGN KEY ("EmpleadoIdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE
);

CREATE TABLE "EvaluacionesDesempeno" (
    "IdEvaluacion" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdEmpleado" integer NOT NULL,
    "FechaEvaluacion" timestamp with time zone NOT NULL,
    "Periodo" text NOT NULL,
    "Puntuacion" numeric NOT NULL,
    "Evaluador" text,
    "Comentarios" text,
    "RutaInforme" text,
    "EmpleadoIdEmpleado" integer NOT NULL,
    CONSTRAINT "PK_EvaluacionesDesempeno" PRIMARY KEY ("IdEvaluacion"),
    CONSTRAINT "FK_EvaluacionesDesempeno_Empleados_EmpleadoIdEmpleado" FOREIGN KEY ("EmpleadoIdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE
);

CREATE TABLE "HistorialDisciplinario" (
    "IdIncidente" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdEmpleado" integer NOT NULL,
    "FechaIncidente" timestamp with time zone NOT NULL,
    "TipoIncidente" text NOT NULL,
    "Descripcion" text NOT NULL,
    "AccionTomada" text NOT NULL,
    "RutaIncidente" text,
    "RegistradoPor" text,
    "FechaRegistro" timestamp with time zone NOT NULL,
    "EmpleadoIdEmpleado" integer NOT NULL,
    CONSTRAINT "PK_HistorialDisciplinario" PRIMARY KEY ("IdIncidente"),
    CONSTRAINT "FK_HistorialDisciplinario_Empleados_EmpleadoIdEmpleado" FOREIGN KEY ("EmpleadoIdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE
);

CREATE TABLE "HistorialPuestos" (
    "IdHistorialPuesto" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdEmpleado" integer NOT NULL,
    "Puesto" character varying(100) NOT NULL,
    "FechaInicioPuesto" timestamp with time zone NOT NULL,
    "FechaFinPuesto" timestamp with time zone,
    CONSTRAINT "PK_HistorialPuestos" PRIMARY KEY ("IdHistorialPuesto"),
    CONSTRAINT "FK_HistorialPuestos_Empleados_IdEmpleado" FOREIGN KEY ("IdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE
);

CREATE TABLE "TrayectoriaEmpleado" (
    "IdHistorialLaboral" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoIdEmpleado" integer NOT NULL,
    "FechaCambio" timestamp with time zone NOT NULL,
    "TipoCambio" character varying(100) NOT NULL,
    "PuestoAnterior" character varying(100),
    "PuestoNuevo" character varying(100),
    "SalarioAnterior" numeric(18,2),
    "SalarioNuevo" numeric(18,2),
    "DepartamentoAnterior" character varying(100),
    "DepartamentoNuevo" character varying(100),
    "MotivoCambio" character varying(500),
    "RegistradoPor" character varying(100),
    "FechaRegistro" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TrayectoriaEmpleado" PRIMARY KEY ("IdHistorialLaboral"),
    CONSTRAINT "FK_TrayectoriaEmpleado_Empleados_EmpleadoIdEmpleado" FOREIGN KEY ("EmpleadoIdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE
);

CREATE INDEX "IX_Atestados_IdPersona" ON "Atestados" ("IdPersona");

CREATE INDEX "IX_CapacitacionesEmpleados_EmpleadoIdEmpleado" ON "CapacitacionesEmpleados" ("EmpleadoIdEmpleado");

CREATE UNIQUE INDEX "IX_Directivos_IdPersona" ON "Directivos" ("IdPersona");

CREATE UNIQUE INDEX "IX_Empleados_IdPersona" ON "Empleados" ("IdPersona");

CREATE INDEX "IX_EvaluacionesDesempeno_EmpleadoIdEmpleado" ON "EvaluacionesDesempeno" ("EmpleadoIdEmpleado");

CREATE INDEX "IX_HistorialDirectivo_IdDirectivo" ON "HistorialDirectivo" ("IdDirectivo");

CREATE INDEX "IX_HistorialDisciplinario_EmpleadoIdEmpleado" ON "HistorialDisciplinario" ("EmpleadoIdEmpleado");

CREATE INDEX "IX_HistorialPuestos_IdEmpleado" ON "HistorialPuestos" ("IdEmpleado");

CREATE INDEX "IX_NivelesEducativos_IdPersona" ON "NivelesEducativos" ("IdPersona");

CREATE UNIQUE INDEX "IX_Personas_DUI" ON "Personas" ("DUI");

CREATE UNIQUE INDEX "IX_Personas_NIT" ON "Personas" ("NIT");

CREATE INDEX "IX_TrayectoriaEmpleado_EmpleadoIdEmpleado" ON "TrayectoriaEmpleado" ("EmpleadoIdEmpleado");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250722225203_InitialFullSchema', '9.0.8');

ALTER TABLE "Personas" ADD "FechaVencimientoDUI" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250804024942_AddedFechaVencimientoDUI', '9.0.8');

ALTER TABLE "Atestados" DROP COLUMN "FechaVencimiento";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250804031442_RemovedFechaVencimientoFromAtestado', '9.0.8');

ALTER TABLE "NivelesEducativos" ALTER COLUMN "TituloObtenido" TYPE character varying(150);
UPDATE "NivelesEducativos" SET "TituloObtenido" = '' WHERE "TituloObtenido" IS NULL;
ALTER TABLE "NivelesEducativos" ALTER COLUMN "TituloObtenido" SET NOT NULL;
ALTER TABLE "NivelesEducativos" ALTER COLUMN "TituloObtenido" SET DEFAULT '';

ALTER TABLE "NivelesEducativos" ALTER COLUMN "Institucion" TYPE character varying(150);
UPDATE "NivelesEducativos" SET "Institucion" = '' WHERE "Institucion" IS NULL;
ALTER TABLE "NivelesEducativos" ALTER COLUMN "Institucion" SET NOT NULL;
ALTER TABLE "NivelesEducativos" ALTER COLUMN "Institucion" SET DEFAULT '';

UPDATE "NivelesEducativos" SET "FechaInicio" = TIMESTAMPTZ '-infinity' WHERE "FechaInicio" IS NULL;
ALTER TABLE "NivelesEducativos" ALTER COLUMN "FechaInicio" SET NOT NULL;
ALTER TABLE "NivelesEducativos" ALTER COLUMN "FechaInicio" SET DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Atestados" ALTER COLUMN "RutaArchivo" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250804142323_AddedNivelEducativo', '9.0.8');

ALTER TABLE "CapacitacionesEmpleados" DROP CONSTRAINT "FK_CapacitacionesEmpleados_Empleados_EmpleadoIdEmpleado";

DROP INDEX "IX_CapacitacionesEmpleados_EmpleadoIdEmpleado";

ALTER TABLE "CapacitacionesEmpleados" DROP COLUMN "EmpleadoIdEmpleado";

CREATE INDEX "IX_CapacitacionesEmpleados_IdEmpleado" ON "CapacitacionesEmpleados" ("IdEmpleado");

ALTER TABLE "CapacitacionesEmpleados" ADD CONSTRAINT "FK_CapacitacionesEmpleados_Empleados_IdEmpleado" FOREIGN KEY ("IdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250804144800_AddedCapacitacionEmpleado', '9.0.8');

ALTER TABLE "HistorialDisciplinario" DROP CONSTRAINT "FK_HistorialDisciplinario_Empleados_EmpleadoIdEmpleado";

DROP INDEX "IX_HistorialDisciplinario_EmpleadoIdEmpleado";

ALTER TABLE "HistorialDisciplinario" DROP COLUMN "EmpleadoIdEmpleado";

ALTER TABLE "HistorialDisciplinario" ALTER COLUMN "TipoIncidente" TYPE character varying(100);

ALTER TABLE "HistorialDisciplinario" ALTER COLUMN "RegistradoPor" TYPE character varying(100);

CREATE INDEX "IX_HistorialDisciplinario_IdEmpleado" ON "HistorialDisciplinario" ("IdEmpleado");

ALTER TABLE "HistorialDisciplinario" ADD CONSTRAINT "FK_HistorialDisciplinario_Empleados_IdEmpleado" FOREIGN KEY ("IdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250804154314_AddedHistorialDisciplinario', '9.0.8');

ALTER TABLE "HistorialDisciplinario" ADD "TipoIncidente_temp" integer;

UPDATE "HistorialDisciplinario" SET "TipoIncidente_temp" = CASE "TipoIncidente" WHEN 'Grave' THEN 0 WHEN 'Leve' THEN 1 ELSE 0 END;

ALTER TABLE "HistorialDisciplinario" DROP COLUMN "TipoIncidente";

ALTER TABLE "HistorialDisciplinario" RENAME COLUMN "TipoIncidente_temp" TO "TipoIncidente";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250804160352_UpdateHistorialDisciplinarioFields', '9.0.8');

ALTER TABLE "EvaluacionesDesempeno" DROP CONSTRAINT "FK_EvaluacionesDesempeno_Empleados_EmpleadoIdEmpleado";

ALTER TABLE "TrayectoriaEmpleado" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "TrayectoriaEmpleado" ADD "CreatedBy" character varying(100);

ALTER TABLE "TrayectoriaEmpleado" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "TrayectoriaEmpleado" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "Personas" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Personas" ADD "CreatedBy" character varying(100);

ALTER TABLE "Personas" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Personas" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "NivelesEducativos" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "NivelesEducativos" ADD "CreatedBy" character varying(100);

ALTER TABLE "NivelesEducativos" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "NivelesEducativos" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "HistorialPuestos" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "HistorialPuestos" ADD "CreatedBy" character varying(100);

ALTER TABLE "HistorialPuestos" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "HistorialPuestos" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "HistorialDisciplinario" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "HistorialDisciplinario" ADD "CreatedBy" character varying(100);

ALTER TABLE "HistorialDisciplinario" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "HistorialDisciplinario" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "HistorialDirectivo" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "HistorialDirectivo" ADD "CreatedBy" character varying(100);

ALTER TABLE "HistorialDirectivo" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "HistorialDirectivo" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "EvaluacionesDesempeno" ALTER COLUMN "EmpleadoIdEmpleado" DROP NOT NULL;

ALTER TABLE "EvaluacionesDesempeno" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "EvaluacionesDesempeno" ADD "CreatedBy" character varying(100);

ALTER TABLE "EvaluacionesDesempeno" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "EvaluacionesDesempeno" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "Empleados" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Empleados" ADD "CreatedBy" character varying(100);

ALTER TABLE "Empleados" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Empleados" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "Directivos" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Directivos" ADD "CreatedBy" character varying(100);

ALTER TABLE "Directivos" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Directivos" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "CapacitacionesEmpleados" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "CapacitacionesEmpleados" ADD "CreatedBy" character varying(100);

ALTER TABLE "CapacitacionesEmpleados" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "CapacitacionesEmpleados" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "Atestados" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Atestados" ADD "CreatedBy" character varying(100);

ALTER TABLE "Atestados" ADD "LastModifiedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Atestados" ADD "LastModifiedBy" character varying(100);

ALTER TABLE "EvaluacionesDesempeno" ADD CONSTRAINT "FK_EvaluacionesDesempeno_Empleados_EmpleadoIdEmpleado" FOREIGN KEY ("EmpleadoIdEmpleado") REFERENCES "Empleados" ("IdEmpleado");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250804161809_AddAuditableProperties', '9.0.8');

ALTER TABLE "EvaluacionesDesempeno" DROP CONSTRAINT "FK_EvaluacionesDesempeno_Empleados_EmpleadoIdEmpleado";

DROP INDEX "IX_EvaluacionesDesempeno_EmpleadoIdEmpleado";

ALTER TABLE "EvaluacionesDesempeno" DROP COLUMN "EmpleadoIdEmpleado";

CREATE INDEX "IX_EvaluacionesDesempeno_IdEmpleado" ON "EvaluacionesDesempeno" ("IdEmpleado");

ALTER TABLE "EvaluacionesDesempeno" ADD CONSTRAINT "FK_EvaluacionesDesempeno_Empleados_IdEmpleado" FOREIGN KEY ("IdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250804165654_AddedEvaluacionesDesempeno', '9.0.8');

ALTER TABLE "NivelesEducativos" ALTER COLUMN "GradoAcademico" TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250804174646_FixedNivelEducativoGradoAcademicoConversion', '9.0.8');

ALTER TABLE "Empleados" ADD "Agencia" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250810045022_AddedAgenciaToEmpleado', '9.0.8');

ALTER TABLE "NivelesEducativos" ALTER COLUMN "FechaInicio" DROP NOT NULL;

ALTER TABLE "CapacitacionesEmpleados" ALTER COLUMN "IdEmpleado" DROP NOT NULL;

ALTER TABLE "CapacitacionesEmpleados" ADD "IdDirectivo" integer;

CREATE INDEX "IX_CapacitacionesEmpleados_IdDirectivo" ON "CapacitacionesEmpleados" ("IdDirectivo");

ALTER TABLE "CapacitacionesEmpleados" ADD CONSTRAINT "FK_CapacitacionesEmpleados_Directivos_IdDirectivo" FOREIGN KEY ("IdDirectivo") REFERENCES "Directivos" ("IdDirectivo") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250812145045_UpdateCapacitacionEmpleadoForDirectivo', '9.0.8');

ALTER TABLE "CapacitacionesEmpleados" DROP CONSTRAINT "FK_CapacitacionesEmpleados_Directivos_IdDirectivo";

ALTER TABLE "CapacitacionesEmpleados" DROP CONSTRAINT "FK_CapacitacionesEmpleados_Empleados_IdEmpleado";

DROP INDEX "IX_CapacitacionesEmpleados_IdDirectivo";

ALTER TABLE "CapacitacionesEmpleados" DROP COLUMN "IdDirectivo";

ALTER TABLE "CapacitacionesEmpleados" RENAME COLUMN "IdEmpleado" TO "EmpleadoIdEmpleado";

ALTER INDEX "IX_CapacitacionesEmpleados_IdEmpleado" RENAME TO "IX_CapacitacionesEmpleados_EmpleadoIdEmpleado";

ALTER TABLE "CapacitacionesEmpleados" ADD "IdPersona" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_CapacitacionesEmpleados_IdPersona" ON "CapacitacionesEmpleados" ("IdPersona");

ALTER TABLE "CapacitacionesEmpleados" ADD CONSTRAINT "FK_CapacitacionesEmpleados_Empleados_EmpleadoIdEmpleado" FOREIGN KEY ("EmpleadoIdEmpleado") REFERENCES "Empleados" ("IdEmpleado");

ALTER TABLE "CapacitacionesEmpleados" ADD CONSTRAINT "FK_CapacitacionesEmpleados_Personas_IdPersona" FOREIGN KEY ("IdPersona") REFERENCES "Personas" ("IdPersona") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250812181934_UpdateCapacitacionToPersona', '9.0.8');

CREATE TABLE "ApplicationRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_ApplicationRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "ApplicationUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text NOT NULL,
    "PasswordHash" text NOT NULL,
    CONSTRAINT "PK_ApplicationUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "ApplicationUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_ApplicationUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_ApplicationUserRoles_ApplicationRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "ApplicationRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ApplicationUserRoles_ApplicationUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "ApplicationUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ApplicationUserRoles_RoleId" ON "ApplicationUserRoles" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250813021738_AddedIdentityModels', '9.0.8');

INSERT INTO "ApplicationRoles" ("Id", "Name")
VALUES (1, 'Administrador');
INSERT INTO "ApplicationRoles" ("Id", "Name")
VALUES (2, 'Consulta');

INSERT INTO "ApplicationUsers" ("Id", "UserName", "PasswordHash")
VALUES (1, 'admin', 'AQAAAAIAAYagAAAAEBp7CmygNDoiqWvD46m43y3y1ntqw7TiRpX4IbowYf+fkYZSanYnxfiODvFsa6R7+g==');
INSERT INTO "ApplicationUsers" ("Id", "UserName", "PasswordHash")
VALUES (2, 'consulta', 'AQAAAAIAAYagAAAAEE9GMbMRE7iX3oXe2/CDS2nJI/Sl3NuE9QokGLnnq3fM5HJjRuY/4GXEyIuGlP61UQ==');

INSERT INTO "ApplicationUserRoles" ("UserId", "RoleId")
VALUES (1, 1);
INSERT INTO "ApplicationUserRoles" ("UserId", "RoleId")
VALUES (2, 2);

SELECT setval(
    pg_get_serial_sequence('"ApplicationRoles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "ApplicationRoles") + 1,
        nextval(pg_get_serial_sequence('"ApplicationRoles"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"ApplicationUsers"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "ApplicationUsers") + 1,
        nextval(pg_get_serial_sequence('"ApplicationUsers"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250813030935_SeedTestUsers', '9.0.8');

CREATE TABLE "Incapacidades" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdEmpleado" integer NOT NULL,
    "FechaInicio" timestamp with time zone NOT NULL,
    "FechaFin" timestamp with time zone NOT NULL,
    "Motivo" text NOT NULL,
    "Comentarios" text NOT NULL,
    "CreatedBy" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastModifiedBy" character varying(100),
    "LastModifiedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Incapacidades" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Incapacidades_Empleados_IdEmpleado" FOREIGN KEY ("IdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE
);

CREATE TABLE "Permisos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdEmpleado" integer NOT NULL,
    "FechaSolicitud" timestamp with time zone NOT NULL,
    "FechaInicio" timestamp with time zone NOT NULL,
    "FechaFin" timestamp with time zone NOT NULL,
    "Motivo" text NOT NULL,
    "Aprobado" boolean NOT NULL,
    "Comentarios" text NOT NULL,
    "CreatedBy" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastModifiedBy" character varying(100),
    "LastModifiedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Permisos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Permisos_Empleados_IdEmpleado" FOREIGN KEY ("IdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE
);

CREATE TABLE "Vacaciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdEmpleado" integer NOT NULL,
    "FechaSolicitud" timestamp with time zone NOT NULL,
    "FechaInicio" timestamp with time zone NOT NULL,
    "FechaFin" timestamp with time zone NOT NULL,
    "Aprobado" boolean NOT NULL,
    "Comentarios" text NOT NULL,
    "CreatedBy" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastModifiedBy" character varying(100),
    "LastModifiedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Vacaciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vacaciones_Empleados_IdEmpleado" FOREIGN KEY ("IdEmpleado") REFERENCES "Empleados" ("IdEmpleado") ON DELETE CASCADE
);

CREATE INDEX "IX_Incapacidades_IdEmpleado" ON "Incapacidades" ("IdEmpleado");

CREATE INDEX "IX_Permisos_IdEmpleado" ON "Permisos" ("IdEmpleado");

CREATE INDEX "IX_Vacaciones_IdEmpleado" ON "Vacaciones" ("IdEmpleado");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250819225622_AddedIncapacidadesPermisosVacaciones', '9.0.8');

ALTER TABLE "Vacaciones" ALTER COLUMN "Comentarios" DROP NOT NULL;

ALTER TABLE "Vacaciones" ADD "FechasNoConsecutivas" text;

ALTER TABLE "Permisos" ALTER COLUMN "Comentarios" DROP NOT NULL;

ALTER TABLE "Incapacidades" ALTER COLUMN "Comentarios" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250821200010_AddedFechasNoConsecutivasToVacacion', '9.0.8');

ALTER TABLE "Vacaciones" ADD "SonConsecutivas" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250822024221_AddedSonConsecutivasToVacacion', '9.0.8');

ALTER TABLE "Personas" ALTER COLUMN "Genero" TYPE integer USING
                CASE
                    WHEN "Genero" = 'Masculino' THEN 0
                    WHEN "Genero" = 'Femenino' THEN 1
                    ELSE 0
                END;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250908152017_UpdatedGeneroToEnum', '9.0.8');

ALTER TABLE "Personas" ALTER COLUMN "TipoAFP" TYPE integer USING
                CASE
                    WHEN "TipoAFP" = 'AFP Crecer' THEN 0
                    WHEN "TipoAFP" = 'AFP Confia' THEN 1
                    ELSE NULL
                END;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250908153212_UpdatedTipoAFPToEnum', '9.0.8');

ALTER TABLE "HistorialDisciplinario" ADD "IdPersona" integer NOT NULL DEFAULT 0;

ALTER TABLE "HistorialDisciplinario" ADD "PersonaIdPersona" integer;

CREATE INDEX "IX_HistorialDisciplinario_PersonaIdPersona" ON "HistorialDisciplinario" ("PersonaIdPersona");

ALTER TABLE "HistorialDisciplinario" ADD CONSTRAINT "FK_HistorialDisciplinario_Personas_PersonaIdPersona" FOREIGN KEY ("PersonaIdPersona") REFERENCES "Personas" ("IdPersona");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250909174610_AddIdPersona', '9.0.8');

ALTER TABLE "EvaluacionesDesempeno" ADD "IdPersona" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250909222636_AddedIdPersonaToEvaluacionDesempeno', '9.0.8');

CREATE INDEX "IX_EvaluacionesDesempeno_IdPersona" ON "EvaluacionesDesempeno" ("IdPersona");

ALTER TABLE "EvaluacionesDesempeno" ADD CONSTRAINT "FK_EvaluacionesDesempeno_Personas_IdPersona" FOREIGN KEY ("IdPersona") REFERENCES "Personas" ("IdPersona") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250909223709_ConfigureForeignKeyForPersonaInEvaluacion', '9.0.8');

ALTER TABLE "Vacaciones" ALTER COLUMN "Comentarios" TYPE character varying(500);

ALTER TABLE "Vacaciones" ADD "DiasSolicitados" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250910174752_AddDiasSolicitadosToVacacion', '9.0.8');

ALTER TABLE "Vacaciones" ALTER COLUMN "FechaInicio" DROP NOT NULL;

ALTER TABLE "Vacaciones" ALTER COLUMN "FechaFin" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250910225453_MadeVacacionDatesNullable', '9.0.8');

ALTER TABLE "Directivos" ADD "Estado" integer NOT NULL DEFAULT 0;

ALTER TABLE "Directivos" ADD "MotivoInactivacion" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250916225137_AddEstadoToDirectivo', '9.0.8');

DROP INDEX "IX_Directivos_IdPersona";

CREATE INDEX "IX_Directivos_IdPersona" ON "Directivos" ("IdPersona");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250921044315_ChangedDirectivoRelationshipToHasMany', '9.0.8');

ALTER TABLE "ApplicationUsers" ADD "IsBlocked" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250923042747_AddIsBlockedToApplicationUser', '9.0.8');

COMMIT;

