// <auto-generated />
using System;
using AcaciRRHH.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcaciRRHH.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250908152017_UpdatedGeneroToEnum")]
    partial class UpdatedGeneroToEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcaciRRHH.Web.Models.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRoles");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ApplicationUserRoles");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Atestado", b =>
                {
                    b.Property<int>("IdAtestado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAtestado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExtensionArchivo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreOriginalArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SubidoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoAtestado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdAtestado");

                    b.HasIndex("IdPersona");

                    b.ToTable("Atestados");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.CapacitacionEmpleado", b =>
                {
                    b.Property<int>("IdCapacitacionEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCapacitacionEmpleado"));

                    b.Property<bool>("CertificadoObtenido")
                        .HasColumnType("boolean");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("EmpleadoIdEmpleado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("Institucion")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaCertificado")
                        .HasColumnType("text");

                    b.HasKey("IdCapacitacionEmpleado");

                    b.HasIndex("EmpleadoIdEmpleado");

                    b.HasIndex("IdPersona");

                    b.ToTable("CapacitacionesEmpleados");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Directivo", b =>
                {
                    b.Property<int>("IdDirectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDirectivo"));

                    b.Property<string>("CargoDirectivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaFinMandato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicioMandato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoMiembro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDirectivo");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Directivos");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpleado"));

                    b.Property<int>("Agencia")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinContrato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotivoFinalizacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TipoFinalizacion")
                        .HasColumnType("integer");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.EvaluacionDesempeno", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Evaluador")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Puntuacion")
                        .HasColumnType("numeric");

                    b.Property<string>("RutaInforme")
                        .HasColumnType("text");

                    b.HasKey("IdEvaluacion");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("EvaluacionesDesempeno");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.HistorialDirectivo", b =>
                {
                    b.Property<int>("IdHistorialDirectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialDirectivo"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaFinMandato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicioMandato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdDirectivo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TipoMandato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("");

                    b.HasKey("IdHistorialDirectivo");

                    b.HasIndex("IdDirectivo");

                    b.ToTable("HistorialDirectivo");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.HistorialDisciplinario", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIncidente"));

                    b.Property<string>("AccionTomada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaIncidente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RutaIncidente")
                        .HasColumnType("text");

                    b.Property<int>("TipoIncidente")
                        .HasColumnType("integer");

                    b.HasKey("IdIncidente");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("HistorialDisciplinario");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.HistorialPuesto", b =>
                {
                    b.Property<int>("IdHistorialPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialPuesto"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaFinPuesto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicioPuesto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdHistorialPuesto");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("HistorialPuestos");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Incapacidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Incapacidades");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.NivelEducativo", b =>
                {
                    b.Property<int>("IdNivelEducativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNivelEducativo"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradoAcademico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TituloObtenido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("IdNivelEducativo");

                    b.HasIndex("IdPersona");

                    b.ToTable("NivelesEducativos");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("boolean");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DUI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoDUI")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NIT")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroAFP")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("TipoAFP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdPersona");

                    b.HasIndex("DUI")
                        .IsUnique();

                    b.HasIndex("NIT")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.TrayectoriaEmpleado", b =>
                {
                    b.Property<int>("IdHistorialLaboral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialLaboral"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DepartamentoAnterior")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DepartamentoNuevo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("EmpleadoIdEmpleado");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotivoCambio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PuestoAnterior")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PuestoNuevo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("SalarioAnterior")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SalarioNuevo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TipoCambio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdHistorialLaboral");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("TrayectoriaEmpleado");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Vacacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("boolean");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FechasNoConsecutivas")
                        .HasColumnType("text");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("SonConsecutivas")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Vacaciones");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcaciRRHH.Web.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Atestado", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Persona", "Persona")
                        .WithMany("Atestados")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.CapacitacionEmpleado", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Empleado", null)
                        .WithMany("Capacitaciones")
                        .HasForeignKey("EmpleadoIdEmpleado");

                    b.HasOne("AcaciRRHH.Web.Models.Persona", "Persona")
                        .WithMany("Capacitaciones")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Directivo", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Persona", "Persona")
                        .WithOne("Directivo")
                        .HasForeignKey("AcaciRRHH.Web.Models.Directivo", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Empleado", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Persona", "Persona")
                        .WithOne("Empleado")
                        .HasForeignKey("AcaciRRHH.Web.Models.Empleado", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.EvaluacionDesempeno", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Empleado", "Empleado")
                        .WithMany("EvaluacionesDesempeno")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.HistorialDirectivo", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Directivo", "Directivo")
                        .WithMany("HistorialDirectivo")
                        .HasForeignKey("IdDirectivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directivo");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.HistorialDisciplinario", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Empleado", "Empleado")
                        .WithMany("HistorialDisciplinario")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.HistorialPuesto", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Empleado", "Empleado")
                        .WithMany("HistorialPuestos")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Incapacidad", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Empleado", "Empleado")
                        .WithMany("Incapacidades")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.NivelEducativo", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Persona", "Persona")
                        .WithMany("NivelesEducativos")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Permiso", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Empleado", "Empleado")
                        .WithMany("Permisos")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.TrayectoriaEmpleado", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Empleado", "Empleado")
                        .WithMany("HistorialTrayectoria")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Vacacion", b =>
                {
                    b.HasOne("AcaciRRHH.Web.Models.Empleado", "Empleado")
                        .WithMany("Vacaciones")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Directivo", b =>
                {
                    b.Navigation("HistorialDirectivo");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Empleado", b =>
                {
                    b.Navigation("Capacitaciones");

                    b.Navigation("EvaluacionesDesempeno");

                    b.Navigation("HistorialDisciplinario");

                    b.Navigation("HistorialPuestos");

                    b.Navigation("HistorialTrayectoria");

                    b.Navigation("Incapacidades");

                    b.Navigation("Permisos");

                    b.Navigation("Vacaciones");
                });

            modelBuilder.Entity("AcaciRRHH.Web.Models.Persona", b =>
                {
                    b.Navigation("Atestados");

                    b.Navigation("Capacitaciones");

                    b.Navigation("Directivo");

                    b.Navigation("Empleado");

                    b.Navigation("NivelesEducativos");
                });
#pragma warning restore 612, 618
        }
    }
}
